### PR TITLE
Add FIDO support

### PR DESCRIPTION
**Pull request by bunnie**
This PR adds FIDO report descriptors.

The descriptors have been tested on live hardware against the CTAP2 testbench and [no compliance issues were found](https://ci.betrusted.io/job/ctap2-tests/25/artifact/Precursor_c7589783a285c.md/*view*/).

### CODE REVIEW

**Comment by dlkj** [comment]
Hi @bunnie. Thanks for the contribution.

To include the `FidoInterface` in the library I'd want to have a stronger encapsulation of the read and write report formats than just a `[u8; 64]`. From a quick scan of the [FIDO U2F HID Protocol Spec](https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-u2f-hid-protocol-ps-20141009.html), there are two types of packet with a fixed field layout, initialization packets and continuation packets. This looks like it would naturally map onto a rust `enum`. Even better would be the ability to read and write U2FHID commands with the mapping onto init and continuation packets handled by the interface.

I'd be happy to have this on a development branch and merge this into main once the higher level functionality is added or  keep the pull request open until the interface supports higher level operations.

I'd be interested in work with you on this, but I'm unlikely to find the time until later on in the year.

**Comment by dlkj** [comment]
...or you could rename this to a `RawFidoInterface` taking a `[u8;64]` for read and write report, leaving the name `FidoInterface` to be implemented later with higher level protocol support.

**Comment by bunnie** [comment]
Sure thing! I just did that. 

The reason we went with opaque packets is because that's [what OpenSK was expecting](https://github.com/google/OpenSK/blob/f2496a8e6d71a4e838884996a1c9b62121f87df2/src/ctap/hid/mod.rs#L39). I also originally had more structure in the packets -- there's two forms that packets can take, initialization or continuation, and it depends on the value of a high bit at offset 4 -- but since OpenSK [already had code to handle this](https://github.com/google/OpenSK/blob/f2496a8e6d71a4e838884996a1c9b62121f87df2/src/ctap/hid/mod.rs#L357-L379), it was more efficient to just shuttle raw packets to and from their stack.

But I agree not all implementations will take this form so making space for both representations might be a good option?

**Comment by dlkj** [comment]
@bunnie - available in 0.2.1 - https://crates.io/crates/usbd-human-interface-device/0.2.1

**Pull request merged**
